name: Qodana

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.2
        with:
          args: --ide,QDHP
